FROM tiangolo/uwsgi-nginx:python3.9

#################
# IMAGE METADATA
#################

# Original image author
LABEL original-author="Sebastian Ramirez <tiangolo@gmail.com>"
# Maintainer of customisations in this file
LABEL customised_image_maintainer="Kody Moodley <k.moodley@esciencecenter.nl>"
# Organisation or affiliation of customised image author
LABEL nl.esciencecenter.image.vendor="The Netherlands eScience Center"
# Version number of customised image
LABEL nl.esciencecenter.image.version="1.0"
# Description of the customised image
LABEL nl.esciencecenter.image.description="\
\
This image runs a pipeline of classification and analysis operations on \
input textual documents (EU legislation) in PDF and HTML format. \
It also generates some analysis files which can be further processed and analysed. \
The goal of the pipeline is to identify, count and analyse the regulatory statements, \
also called legal obligations, in the input documents. This output is part of the \
Nature of EU Rules project: http://research-software-directory.org/projects/the-nature-of-eu-rules-strict-and-detailed-or-lacking-bite \
\
"
# Description of inputs required by customised image
LABEL nl.esciencecenter.image.inputs=" \
\
1. A directory named 'data/' in the same directory as this Docker file containing EU legislation documents in PDF and / or HTML format. \
The filenames must be the CELEX number (http://eur-lex.europa.eu/content/help/eurlex-content/celex-number.html) of the legislation \
2. A CSV file named 'metadata.csv' in the same directory as this Docker file either generated by the corresponding script in this repo: https://github.com/nature-of-eu-rules/data-extraction \
or having the same format or columns as specified there. \
\
"
# Description of output files generated in this image
LABEL nl.esciencecenter.image.outputs=" \
\
1. A directory named '/app/eu-legislation-strictness-analysis/generated-files/' containing analysis plots in .svg image format and .html interactive format. \
2. A CSV file named 'classified-sentences.csv' located in '/app/regulatory-statement-classification/' which stores the results of classifying each individual sentence as either regulatory or not. \
3. A CSV file named 'enriched-metadata.csv' located in '/app/eu-legislation-strictness-analysis/' which adds a column to the input 'metadata.csv' file storing the counts of regulatory statements in each document. \
This is the main file used as the basis for analysis. \
\
"

#####################
# INSTALL BASIC TOOLS 
#####################

# Install apt-get and nano text editor 
# (for verifying the contents of output files when shelling into the container)
RUN apt-get update
RUN apt-get install nano -y
# Install zip and unzip archive creation and extraction tools
RUN apt-get install zip unzip -y

#########################################
# EXECUTION of EU RULES ANALYSIS PIPELINE
#########################################

######################################################
# STEP 1: Data-preprocessing
# Description: extracts sentences from input documents
######################################################
# Clone repo for this component of the pipeline
RUN git clone http://github.com/nature-of-eu-rules/data-preprocessing.git
# Set working directory to root of cloned repo
WORKDIR /app/data-preprocessing
# Copy data from host to container (insider cloned repo folder)
COPY data/ /app/data-preprocessing/data
# Copy requirements file with all Python libraries required for pipeline
COPY requirements-full.txt .
# Install required libraries
RUN pip install -r requirements-full.txt
# Start nginx server (to have a process that continuously runs so that we can shell into the container if needed)
CMD ["/start.sh"]
# Run sentence extraction script
RUN python extract_sentences.py -in data/ -out sentences.csv
# Copy output of Step 1 of the pipeline to root of container (app directory)
COPY sentences.csv /app

###############################################################
# STEP 2: Classification of regulatory statements
# Description: classifies sentences as either regulatory or not
###############################################################
# First change back to root directory
WORKDIR /app
# Clone repo for this component of the pipeline
RUN git clone http://github.com/nature-of-eu-rules/regulatory-statement-classification.git
# Set working directory to root of cloned repo
WORKDIR /app/regulatory-statement-classification
# Run sentence classification script
RUN python rule-based-classification.py -in ../data-preprocessing/sentences.csv -out classified-sentences.csv -agts data/agent_nouns.json

#########################################################################################
# STEP 3: Analyse the classified sentences 
# Description: enrich document metadata file with counts per doc of regulatory statements
#              and generate plots for analysis automatically
#########################################################################################
# First change back to root directory
WORKDIR /app
# Clone repo for this component of the pipeline
RUN git clone http://github.com/nature-of-eu-rules/eu-legislation-strictness-analysis.git
# Set working directory to root of cloned repo
WORKDIR /app/eu-legislation-strictness-analysis

# 3a: Enrich metadata with number of regulatory statements
# Copy EU legislation document metadata here, it is needed for the analysis
COPY metadata.csv .
# Run metadata enrichment script (enriches metadata file with number of regulatory statements in each document amongst other things)
RUN python prepare-data-for-analysis.py -m metadata.csv -c ../regulatory-statement-classification/classified-sentences.csv -o enriched-metadata.csv

# 3b: Do the analysis
# Generate images and interactive plots for analysis of regulatory statement frequency
RUN python analysis.py -in enriched-metadata.csv -sm count -out generated-files/

# Change back to root directory
WORKDIR /app

# Save all results files in one zip archive for user convenience
RUN zip -r eurules-analysis.zip /app/eu-legislation-strictness-analysis/generated-files/ /app/regulatory-statement-classification/classified-sentences.csv /app/eu-legislation-strictness-analysis/enriched-metadata.csv


